# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PdOzvV3RGLsGaNC6u9-whWVXhF_m5WLo
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

df = pd.read_csv('/content/heart_disease_data.csv')

df.head()

df.tail()

df.shape

df.info()

df.describe()

df['target'].value_counts()

X = df.drop(columns= 'target',axis=1)

X

Y = df['target']

Y

X_train,X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=23)

print(X_test.shape, X_train.shape)

model = LogisticRegression()

model.fit(X_train, Y_train)

Y_pred = model.predict(X_test)

Y_train

accuracy_score(Y_test,Y_pred)

input_data = (58,0,2,120,340,0,1,172,0,0,2,0,2)

arr = np.array(input_data)

prediction = model.predict(arr.reshape(1,-1))

print(prediction)

if prediction == 1:
  print('consult your doctor')
else:
  print('you are healthy')

